In [103]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(torch.nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2,2, bias=False)  # 5*5 from image dimensio

    def forward(self, x):
        x = self.fc1(x)
        return x


net = Net()
print(net)

Net(
  (fc1): Linear(in_features=2, out_features=2, bias=False)
)


In [104]:
X = torch.rand(100,2)
y = torch.concat(([X[:,(1,)],X[:,(0,)]]), dim=1)

In [105]:
a = torch.rand(1)*256
a = a.long()
X[a,:]

IndexError: index 215 is out of bounds for dimension 0 with size 100

In [106]:
import torch.optim as optim

criterion = nn.MSELoss()

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.0001)
samples = 10000
for _ in range(samples):
    rand_row = a = torch.rand(1)*X.shape[0]
    rand_row = rand_row.long()
    optimizer.zero_grad()   # zero the gradient buffers
    output = net(X[rand_row:rand_row+5, :])
    loss = criterion(output, y[rand_row:rand_row+5, :])
    print(loss)
    loss.backward()
    optimizer.step()

tensor(0.3410, grad_fn=<MseLossBackward0>)
tensor(0.3877, grad_fn=<MseLossBackward0>)
tensor(0.4245, grad_fn=<MseLossBackward0>)
tensor(0.4545, grad_fn=<MseLossBackward0>)
tensor(0.6132, grad_fn=<MseLossBackward0>)
tensor(0.5052, grad_fn=<MseLossBackward0>)
tensor(0.4543, grad_fn=<MseLossBackward0>)
tensor(0.4659, grad_fn=<MseLossBackward0>)
tensor(0.4334, grad_fn=<MseLossBackward0>)
tensor(0.2383, grad_fn=<MseLossBackward0>)
tensor(0.5128, grad_fn=<MseLossBackward0>)
tensor(0.5672, grad_fn=<MseLossBackward0>)
tensor(0.2839, grad_fn=<MseLossBackward0>)
tensor(0.4753, grad_fn=<MseLossBackward0>)
tensor(0.2550, grad_fn=<MseLossBackward0>)
tensor(0.5670, grad_fn=<MseLossBackward0>)
tensor(0.4925, grad_fn=<MseLossBackward0>)
tensor(0.3958, grad_fn=<MseLossBackward0>)
tensor(0.7003, grad_fn=<MseLossBackward0>)
tensor(0.4825, grad_fn=<MseLossBackward0>)
tensor(0.4116, grad_fn=<MseLossBackward0>)
tensor(0.4655, grad_fn=<MseLossBackward0>)
tensor(0.4115, grad_fn=<MseLossBackward0>)
tensor(0.53

In [102]:
net.fc1.weight

Parameter containing:
tensor([[6.2436e-06, 9.9999e-01],
        [9.9999e-01, 6.3266e-06]], requires_grad=True)

In [91]:
for _ in range(10):
    rand_row = a = torch.rand(1)*X.shape[0]
    rand_row = rand_row.long()
    output = net(X[rand_row, :])
    print(X[rand_row, :])
    print(output)
    print(y[rand_row, :])
    print(loss)

tensor([0.0803, 0.8329])
tensor([0.8329, 0.0803], grad_fn=<SqueezeBackward3>)
tensor([0.8329, 0.0803])
tensor(2.5555e-11, grad_fn=<MseLossBackward0>)
tensor([0.0803, 0.8329])
tensor([0.8329, 0.0803], grad_fn=<SqueezeBackward3>)
tensor([0.8329, 0.0803])
tensor(2.5555e-11, grad_fn=<MseLossBackward0>)
tensor([0.0803, 0.8329])
tensor([0.8329, 0.0803], grad_fn=<SqueezeBackward3>)
tensor([0.8329, 0.0803])
tensor(2.5555e-11, grad_fn=<MseLossBackward0>)
tensor([0.0803, 0.8329])
tensor([0.8329, 0.0803], grad_fn=<SqueezeBackward3>)
tensor([0.8329, 0.0803])
tensor(2.5555e-11, grad_fn=<MseLossBackward0>)
tensor([0.0803, 0.8329])
tensor([0.8329, 0.0803], grad_fn=<SqueezeBackward3>)
tensor([0.8329, 0.0803])
tensor(2.5555e-11, grad_fn=<MseLossBackward0>)
tensor([0.0803, 0.8329])
tensor([0.8329, 0.0803], grad_fn=<SqueezeBackward3>)
tensor([0.8329, 0.0803])
tensor(2.5555e-11, grad_fn=<MseLossBackward0>)
tensor([0.0803, 0.8329])
tensor([0.8329, 0.0803], grad_fn=<SqueezeBackward3>)
tensor([0.8329, 0.0803

In [94]:
net.fc1.weight

Parameter containing:
tensor([[-0.6364,  1.0613],
        [-0.3224,  0.1275]], requires_grad=True)

In [95]:
net.fc1.bias